name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - master

    # on: push    # Default will running for every branch.

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:

      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v1

      - name: Create Firebase File
        uses: 1arp/create-a-file-action@0.2
        with:
          path: 'android/app'
          file: 'google-services.json'
          content: ${{secrets.FIREBASE_API_KEY}}

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter

      # Get flutter dependencies.
      - run: flutter pub get

#      # Check for any formatting issues in the code.
#      - run: flutter format --set-exit-if-changed .

      # Build apk.
      - run: flutter build apk

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Create a Release APK
        uses: marvinpinto/action-automatic-releases@latest
        with:
          files: "build/app/outputs/apk/release/*.apk"
          automatic_release_tag: "latest"
          prerelease: false          
          repo_token: ${{ secrets.GITHUB_TOKEN }}
